ALTER TABLE "post_lock_adjustments" DROP CONSTRAINT "post_lock_adjustments_non_zero_minutes";--> statement-breakpoint
ALTER TABLE "correction_requests" ADD COLUMN "locked_monthly_snapshot_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "correction_request_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "correction_decision_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "applied_correction_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "adjustment_version" integer;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "previous_adjusted_worked_minutes" integer;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "proposed_worked_minutes" integer;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "reverses_adjustment_id" uuid;--> statement-breakpoint
ALTER TABLE "correction_requests" ADD CONSTRAINT "correction_requests_locked_monthly_snapshot_id_approved_monthly_snapshots_id_fk" FOREIGN KEY ("locked_monthly_snapshot_id") REFERENCES "public"."approved_monthly_snapshots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_correction_request_id_correction_requests_id_fk" FOREIGN KEY ("correction_request_id") REFERENCES "public"."correction_requests"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_correction_decision_id_correction_decisions_id_fk" FOREIGN KEY ("correction_decision_id") REFERENCES "public"."correction_decisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_applied_correction_id_applied_corrections_id_fk" FOREIGN KEY ("applied_correction_id") REFERENCES "public"."applied_corrections"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_reversal_fk" FOREIGN KEY ("reverses_adjustment_id") REFERENCES "public"."post_lock_adjustments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "correction_requests_locked_snapshot_idx" ON "correction_requests" USING btree ("locked_monthly_snapshot_id");--> statement-breakpoint
CREATE UNIQUE INDEX "post_lock_adjustments_applied_correction_uidx" ON "post_lock_adjustments" USING btree ("applied_correction_id");--> statement-breakpoint
CREATE UNIQUE INDEX "post_lock_adjustments_snapshot_version_uidx" ON "post_lock_adjustments" USING btree ("monthly_snapshot_id","adjustment_version");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_linkage_shape" CHECK (("post_lock_adjustments"."correction_request_id" is null and "post_lock_adjustments"."correction_decision_id" is null and "post_lock_adjustments"."applied_correction_id" is null and "post_lock_adjustments"."adjustment_version" is null and "post_lock_adjustments"."previous_adjusted_worked_minutes" is null and "post_lock_adjustments"."proposed_worked_minutes" is null) or ("post_lock_adjustments"."correction_request_id" is not null and "post_lock_adjustments"."correction_decision_id" is not null and "post_lock_adjustments"."applied_correction_id" is not null and "post_lock_adjustments"."adjustment_version" is not null and "post_lock_adjustments"."previous_adjusted_worked_minutes" is not null and "post_lock_adjustments"."proposed_worked_minutes" is not null));--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_worked_delta_reconciles" CHECK ("post_lock_adjustments"."previous_adjusted_worked_minutes" is null or ("post_lock_adjustments"."previous_adjusted_worked_minutes" >= 0 and "post_lock_adjustments"."proposed_worked_minutes" >= 0 and "post_lock_adjustments"."minutes" = "post_lock_adjustments"."proposed_worked_minutes" - "post_lock_adjustments"."previous_adjusted_worked_minutes"));--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_positive_version" CHECK ("post_lock_adjustments"."adjustment_version" is null or "post_lock_adjustments"."adjustment_version" > 0);--> statement-breakpoint
ALTER TABLE "applied_corrections" ADD CONSTRAINT "applied_corrections_organization_identity_unique" UNIQUE ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_organization_identity_unique" UNIQUE ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "correction_requests" ADD CONSTRAINT "correction_requests_locked_snapshot_organization_fk" FOREIGN KEY ("organization_id", "locked_monthly_snapshot_id") REFERENCES "approved_monthly_snapshots" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "applied_corrections" ADD CONSTRAINT "applied_corrections_request_organization_fk" FOREIGN KEY ("organization_id", "correction_request_id") REFERENCES "correction_requests" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "applied_corrections" ADD CONSTRAINT "applied_corrections_decision_organization_fk" FOREIGN KEY ("organization_id", "correction_decision_id") REFERENCES "correction_decisions" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "applied_corrections" ADD CONSTRAINT "applied_corrections_employee_organization_fk" FOREIGN KEY ("organization_id", "employee_id") REFERENCES "employees" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_employee_organization_fk" FOREIGN KEY ("organization_id", "employee_id") REFERENCES "employees" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_request_organization_fk" FOREIGN KEY ("organization_id", "correction_request_id") REFERENCES "correction_requests" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_decision_organization_fk" FOREIGN KEY ("organization_id", "correction_decision_id") REFERENCES "correction_decisions" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_applied_organization_fk" FOREIGN KEY ("organization_id", "applied_correction_id") REFERENCES "applied_corrections" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_reversal_organization_fk" FOREIGN KEY ("organization_id", "reverses_adjustment_id") REFERENCES "post_lock_adjustments" ("organization_id", "id");
