CREATE TABLE "absence_cancellation_snapshot_links" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"organization_id" uuid NOT NULL,
	"absence_cancellation_id" uuid NOT NULL,
	"monthly_snapshot_id" uuid NOT NULL,
	"snapshot_source_fingerprint" varchar(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "absence_cancellation_snapshot_links_source_fingerprint_hex" CHECK ("absence_cancellation_snapshot_links"."snapshot_source_fingerprint" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" DROP CONSTRAINT "post_lock_adjustments_linkage_shape";--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" DROP CONSTRAINT "post_lock_adjustments_worked_delta_reconciles";--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "absence_cancellation_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "absence_cancellation_decision_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "absence_cancellation_snapshot_link_id" uuid;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "worked_minutes_delta" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "absence_credit_minutes_delta" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "expected_minutes_delta" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD COLUMN "credited_minutes_delta" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
UPDATE "post_lock_adjustments"
SET "worked_minutes_delta" = "minutes",
    "credited_minutes_delta" = "minutes"
WHERE "correction_request_id" IS NOT NULL;--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_absence_cancellation_id_absence_cancellations_id_fk" FOREIGN KEY ("absence_cancellation_id") REFERENCES "public"."absence_cancellations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_monthly_snapshot_id_approved_monthly_snapshots_id_fk" FOREIGN KEY ("monthly_snapshot_id") REFERENCES "public"."approved_monthly_snapshots"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "absence_cancellation_snapshot_links_cancellation_snapshot_uidx" ON "absence_cancellation_snapshot_links" USING btree ("absence_cancellation_id","monthly_snapshot_id");--> statement-breakpoint
CREATE INDEX "absence_cancellation_snapshot_links_snapshot_idx" ON "absence_cancellation_snapshot_links" USING btree ("monthly_snapshot_id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_absence_cancellation_id_absence_cancellations_id_fk" FOREIGN KEY ("absence_cancellation_id") REFERENCES "public"."absence_cancellations"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_absence_cancellation_decision_id_absence_cancellation_decisions_id_fk" FOREIGN KEY ("absence_cancellation_decision_id") REFERENCES "public"."absence_cancellation_decisions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_absence_cancellation_snapshot_link_id_absence_cancellation_snapshot_links_id_fk" FOREIGN KEY ("absence_cancellation_snapshot_link_id") REFERENCES "public"."absence_cancellation_snapshot_links"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "post_lock_adjustments_cancellation_link_date_uidx" ON "post_lock_adjustments" USING btree ("absence_cancellation_snapshot_link_id","local_date");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_component_delta_reconciles" CHECK ("post_lock_adjustments"."minutes" = "post_lock_adjustments"."credited_minutes_delta" - "post_lock_adjustments"."expected_minutes_delta");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_correction_component_shape" CHECK ("post_lock_adjustments"."correction_request_id" is null or ("post_lock_adjustments"."worked_minutes_delta" = "post_lock_adjustments"."minutes" and "post_lock_adjustments"."credited_minutes_delta" = "post_lock_adjustments"."minutes" and "post_lock_adjustments"."absence_credit_minutes_delta" = 0 and "post_lock_adjustments"."expected_minutes_delta" = 0));--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_cancellation_component_shape" CHECK ("post_lock_adjustments"."absence_cancellation_id" is null or ("post_lock_adjustments"."worked_minutes_delta" = 0 and "post_lock_adjustments"."absence_credit_minutes_delta" <= 0 and "post_lock_adjustments"."expected_minutes_delta" >= 0 and "post_lock_adjustments"."credited_minutes_delta" = "post_lock_adjustments"."absence_credit_minutes_delta"));--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_linkage_shape" CHECK (("post_lock_adjustments"."correction_request_id" is null and "post_lock_adjustments"."correction_decision_id" is null and "post_lock_adjustments"."applied_correction_id" is null and "post_lock_adjustments"."absence_cancellation_id" is null and "post_lock_adjustments"."absence_cancellation_decision_id" is null and "post_lock_adjustments"."absence_cancellation_snapshot_link_id" is null and "post_lock_adjustments"."adjustment_version" is null and "post_lock_adjustments"."previous_adjusted_worked_minutes" is null and "post_lock_adjustments"."proposed_worked_minutes" is null) or ("post_lock_adjustments"."correction_request_id" is not null and "post_lock_adjustments"."correction_decision_id" is not null and "post_lock_adjustments"."applied_correction_id" is not null and "post_lock_adjustments"."absence_cancellation_id" is null and "post_lock_adjustments"."absence_cancellation_decision_id" is null and "post_lock_adjustments"."absence_cancellation_snapshot_link_id" is null and "post_lock_adjustments"."adjustment_version" is not null and "post_lock_adjustments"."previous_adjusted_worked_minutes" is not null and "post_lock_adjustments"."proposed_worked_minutes" is not null) or ("post_lock_adjustments"."correction_request_id" is null and "post_lock_adjustments"."correction_decision_id" is null and "post_lock_adjustments"."applied_correction_id" is null and "post_lock_adjustments"."absence_cancellation_id" is not null and "post_lock_adjustments"."absence_cancellation_decision_id" is not null and "post_lock_adjustments"."absence_cancellation_snapshot_link_id" is not null and "post_lock_adjustments"."adjustment_version" is not null and "post_lock_adjustments"."previous_adjusted_worked_minutes" is null and "post_lock_adjustments"."proposed_worked_minutes" is null and "post_lock_adjustments"."reverses_adjustment_id" is null));--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_worked_delta_reconciles" CHECK ("post_lock_adjustments"."previous_adjusted_worked_minutes" is null or ("post_lock_adjustments"."previous_adjusted_worked_minutes" >= 0 and "post_lock_adjustments"."proposed_worked_minutes" >= 0 and "post_lock_adjustments"."worked_minutes_delta" = "post_lock_adjustments"."proposed_worked_minutes" - "post_lock_adjustments"."previous_adjusted_worked_minutes"));
--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_organization_identity_unique" UNIQUE ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "absence_cancellations" ADD CONSTRAINT "absence_cancellations_organization_identity_unique" UNIQUE ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "absence_cancellation_decisions" ADD CONSTRAINT "absence_cancellation_decisions_organization_identity_unique" UNIQUE ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_cancellation_organization_fk" FOREIGN KEY ("organization_id", "absence_cancellation_id") REFERENCES "absence_cancellations" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "absence_cancellation_snapshot_links" ADD CONSTRAINT "absence_cancellation_snapshot_links_snapshot_organization_fk" FOREIGN KEY ("organization_id", "monthly_snapshot_id") REFERENCES "approved_monthly_snapshots" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_cancellation_organization_fk" FOREIGN KEY ("organization_id", "absence_cancellation_id") REFERENCES "absence_cancellations" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_cancellation_decision_organization_fk" FOREIGN KEY ("organization_id", "absence_cancellation_decision_id") REFERENCES "absence_cancellation_decisions" ("organization_id", "id");--> statement-breakpoint
ALTER TABLE "post_lock_adjustments" ADD CONSTRAINT "post_lock_adjustments_cancellation_link_organization_fk" FOREIGN KEY ("organization_id", "absence_cancellation_snapshot_link_id") REFERENCES "absence_cancellation_snapshot_links" ("organization_id", "id");--> statement-breakpoint
CREATE TRIGGER absence_cancellation_snapshot_links_immutable BEFORE UPDATE OR DELETE ON "absence_cancellation_snapshot_links" FOR EACH ROW EXECUTE FUNCTION reject_immutable_record_change();
