packages:
  - apps/*
  - packages/*

sharedWorkspaceLockfile: true
linkWorkspacePackages: false
saveWorkspaceProtocol: rolling
savePrefix: ''
disallowWorkspaceCycles: true
engineStrict: true
nodeVersion: 24.18.0
pmOnFail: download
allowBuilds:
  esbuild: true
