export const workspacePackage = '@workledger/contracts' as const;
export const workspaceDependencies = [] as const;

export type WorkspacePackageName = typeof workspacePackage;
export type WorkspaceDependencyName = (typeof workspaceDependencies)[number];

export {
  TEAM_AVAILABILITY_STATES,
  teamAvailabilityStateSchema,
  teamStatusEnvelopeSchema,
  teamStatusMemberSchema,
  teamStatusSchema,
  teamStatusSummarySchema,
  type TeamAvailabilityState,
  type TeamStatus,
  type TeamStatusMember,
} from './team-status.js';

export {
  APPROVAL_INBOX_DIRECTIONS,
  APPROVAL_INBOX_ITEM_STATUSES,
  APPROVAL_INBOX_SORTS,
  APPROVAL_INBOX_STATUSES,
  APPROVAL_INBOX_TYPES,
  APPROVAL_DECISION_ACTIONS,
  APPROVAL_DETAIL_ACTIONS,
  approvalDecisionActionSchema,
  approvalDecisionEnvelopeSchema,
  approvalDecisionRequestSchema,
  approvalDecisionResultSchema,
  approvalDetailActionSchema,
  approvalDetailEnvelopeSchema,
  approvalDetailSchema,
  approvalInboxDirectionSchema,
  approvalInboxEnvelopeSchema,
  approvalInboxFilterOptionsSchema,
  approvalInboxItemSchema,
  approvalInboxItemStatusSchema,
  approvalInboxPaginationSchema,
  approvalInboxQuerySchema,
  approvalInboxSchema,
  approvalInboxSortSchema,
  approvalInboxStatusSchema,
  approvalInboxTeamSchema,
  approvalInboxTypeSchema,
  type ApprovalInbox,
  type ApprovalInboxDirection,
  type ApprovalInboxItem,
  type ApprovalInboxItemStatus,
  type ApprovalInboxQuery,
  type ApprovalInboxSort,
  type ApprovalInboxStatus,
  type ApprovalInboxType,
  type ApprovalDecisionAction,
  type ApprovalDecisionRequest,
  type ApprovalDecisionResult,
  type ApprovalDetail,
  type ApprovalDetailAction,
} from './approvals.js';

export {
  absenceCancellationSchema,
  decideAbsenceCancellationSchema,
  decidedAbsenceCancellationEnvelopeSchema,
  submitAbsenceCancellationSchema,
  submittedAbsenceCancellationEnvelopeSchema,
  withdrawAbsenceCancellationSchema,
  withdrawnAbsenceCancellationEnvelopeSchema,
  type AbsenceCancellation,
  type DecideAbsenceCancellation,
  type SubmitAbsenceCancellation,
  type WithdrawAbsenceCancellation,
} from './absence-cancellations.js';

export {
  personalCalendarAbsenceSchema,
  personalCalendarEnvelopeSchema,
  personalCalendarHolidaySchema,
  personalCalendarQuerySchema,
  personalCalendarSchema,
  type PersonalCalendar,
  type PersonalCalendarQuery,
} from './personal-calendar.js';
export {
  acknowledgeSicknessReportSchema,
  acknowledgedSicknessReportEnvelopeSchema,
  acknowledgedSicknessReportSchema,
  reportedSicknessCoverageSchema,
  submittedSicknessReportEnvelopeSchema,
  submittedSicknessReportSchema,
  submitSicknessReportSchema,
  type AcknowledgeSicknessReport,
  type SubmitSicknessReport,
  type SubmittedSicknessReport,
} from './sickness-reports.js';
export {
  absenceCoverageInputSchema,
  submittedVacationRequestEnvelopeSchema,
  submittedVacationRequestSchema,
  submitVacationRequestSchema,
  vacationRequestCoverageSchema,
  type SubmittedVacationRequest,
  type SubmitVacationRequest,
  type AbsenceCoverageInput,
} from './vacation-requests.js';
export {
  applyCorrectionEnvelopeSchema,
  applyCorrectionRequestSchema,
  correctionRequestIntervalInputSchema,
  correctionDecisionEnvelopeSchema,
  correctionDecisionRequestSchema,
  correctionReviewItemSchema,
  correctionReviewQueueEnvelopeSchema,
  correctionReviewQueueSchema,
  submitCorrectionRequestEnvelopeSchema,
  submitCorrectionRequestSchema,
  submittedCorrectionRequestSchema,
  type SubmitCorrectionRequest,
  type SubmittedCorrectionRequest,
  type CorrectionDecisionRequest,
  type CorrectionReviewItem,
} from './corrections.js';

export {
  APPLICATION_ROLES,
  NAVIGATION_AREAS,
  PASSWORD_MAXIMUM_LENGTH,
  PASSWORD_MINIMUM_LENGTH,
  accountSummarySchema,
  applicationRoleSchema,
  csrfBootstrapEnvelopeSchema,
  csrfBootstrapSchema,
  employeeSelfSummarySchema,
  navigationAreaSchema,
  organizationSummarySchema,
  revokeSelfSessionEnvelopeSchema,
  revokeSelfSessionResultSchema,
  selfContextEnvelopeSchema,
  selfContextSchema,
  selfProfileEnvelopeSchema,
  selfProfileSchema,
  selfSessionSummarySchema,
  type ApplicationRole,
  type NavigationArea,
  type SelfContext,
  type SelfProfile,
  type SelfSessionSummary,
} from './account.js';

export {
  API_ERROR_CODES,
  API_FIELD_ERROR_CODES,
  apiErrorCodeSchema,
  apiErrorEnvelopeSchema,
  apiErrorMetaSchema,
  apiErrorSchema,
  apiFieldErrorCodeSchema,
  apiFieldErrorSchema,
  apiFieldErrorsSchema,
  apiRecoveryContextSchema,
  apiResponseMetaSchema,
  createSuccessEnvelopeSchema,
  requestIdSchema,
  type ApiErrorCode,
  type ApiErrorEnvelope,
  type ApiFieldError,
  type ApiFieldErrorCode,
  type ApiFieldErrors,
  type ApiRecoveryContext,
  type ApiResponseMeta,
} from './api.js';

export {
  ATTENDANCE_COMMANDS,
  ATTENDANCE_STATES,
  CALCULATION_BLOCKER_CODES,
  CALCULATION_WARNING_CODES,
  PUNCH_EVENT_TYPES,
  TODAY_CALCULATION_STATUSES,
  attendanceCommandSchema,
  attendanceCommandResultSchema,
  attendanceStateSchema,
  calculationBlockerCodeSchema,
  calculationWarningCodeSchema,
  clockInEnvelopeSchema,
  clockInRequestSchema,
  clockInResultSchema,
  clockOutEnvelopeSchema,
  clockOutRequestSchema,
  clockOutResultSchema,
  punchEventTypeSchema,
  resumeAttendanceEnvelopeSchema,
  resumeAttendanceRequestSchema,
  resumeAttendanceResultSchema,
  startBreakEnvelopeSchema,
  startBreakRequestSchema,
  startBreakResultSchema,
  todayAttendanceEnvelopeSchema,
  todayAttendanceEstimateSchema,
  todayAttendanceSchema,
  todayAttendanceStateSchema,
  todayCalculationSchema,
  todayCalculationStatusSchema,
  todayTimelineEventSchema,
  type AttendanceCommand,
  type AttendanceCommandResult,
  type AttendanceState,
  type CalculationBlockerCode,
  type CalculationWarningCode,
  type ClockInRequest,
  type ClockInResult,
  type ClockOutRequest,
  type ClockOutResult,
  type ResumeAttendanceRequest,
  type ResumeAttendanceResult,
  type StartBreakRequest,
  type StartBreakResult,
  type TodayAttendance,
  type TodayAttendanceEstimate,
  type TodayTimelineEvent,
} from './today.js';

export {
  MY_TIME_VIEWS,
  LEAVE_ENTITLEMENT_ENTRY_TYPES,
  TIME_ACCOUNT_ENTRY_TYPES,
  TIME_RECORD_STATUSES,
  dailyTimeAttentionSchema,
  dailyTimeCalculationSchema,
  dailyTimeEventSchema,
  dailyTimeIntervalSchema,
  dailyTimeRecordEnvelopeSchema,
  dailyTimeRecordSchema,
  dailyTimeSessionSchema,
  flexibleTimeBalanceSchema,
  leaveBalanceSchema,
  leaveEntitlementAccountSchema,
  leaveEntitlementLedgerEntrySchema,
  leaveEntitlementLedgerPageSchema,
  myTimeEnvelopeSchema,
  myTimePeriodSchema,
  myTimeQuerySchema,
  myTimeSchema,
  myTimeSummarySchema,
  timeAccountLedgerEntrySchema,
  timeAccountLedgerPageSchema,
  timeRecordSchema,
  type FlexibleTimeBalance,
  type LeaveBalance,
  type LeaveEntitlementAccount,
  type LeaveEntitlementLedgerEntry,
  type DailyTimeAttention,
  type DailyTimeRecord,
  type MyTime,
  type MyTimeQuery,
  type MyTimeView,
  type TimeAccountLedgerEntry,
  type TimeRecord,
} from './time.js';
