export const workspacePackage = '@workledger/contracts' as const;
export const workspaceDependencies = [] as const;

export type WorkspacePackageName = typeof workspacePackage;
export type WorkspaceDependencyName = (typeof workspaceDependencies)[number];

export {
  APPLICATION_ROLES,
  NAVIGATION_AREAS,
  PASSWORD_MAXIMUM_LENGTH,
  PASSWORD_MINIMUM_LENGTH,
  accountSummarySchema,
  applicationRoleSchema,
  csrfBootstrapEnvelopeSchema,
  csrfBootstrapSchema,
  employeeSelfSummarySchema,
  navigationAreaSchema,
  organizationSummarySchema,
  revokeSelfSessionEnvelopeSchema,
  revokeSelfSessionResultSchema,
  selfContextEnvelopeSchema,
  selfContextSchema,
  selfProfileEnvelopeSchema,
  selfProfileSchema,
  selfSessionSummarySchema,
  type ApplicationRole,
  type NavigationArea,
  type SelfContext,
  type SelfProfile,
  type SelfSessionSummary,
} from './account.js';

export {
  API_ERROR_CODES,
  API_FIELD_ERROR_CODES,
  apiErrorCodeSchema,
  apiErrorEnvelopeSchema,
  apiErrorMetaSchema,
  apiErrorSchema,
  apiFieldErrorCodeSchema,
  apiFieldErrorSchema,
  apiFieldErrorsSchema,
  apiRecoveryContextSchema,
  apiResponseMetaSchema,
  createSuccessEnvelopeSchema,
  requestIdSchema,
  type ApiErrorCode,
  type ApiErrorEnvelope,
  type ApiFieldError,
  type ApiFieldErrorCode,
  type ApiFieldErrors,
  type ApiRecoveryContext,
  type ApiResponseMeta,
} from './api.js';

export {
  ATTENDANCE_COMMANDS,
  ATTENDANCE_STATES,
  CALCULATION_BLOCKER_CODES,
  CALCULATION_WARNING_CODES,
  PUNCH_EVENT_TYPES,
  TODAY_CALCULATION_STATUSES,
  attendanceCommandSchema,
  attendanceCommandResultSchema,
  attendanceStateSchema,
  calculationBlockerCodeSchema,
  calculationWarningCodeSchema,
  clockInEnvelopeSchema,
  clockInRequestSchema,
  clockInResultSchema,
  clockOutEnvelopeSchema,
  clockOutRequestSchema,
  clockOutResultSchema,
  punchEventTypeSchema,
  resumeAttendanceEnvelopeSchema,
  resumeAttendanceRequestSchema,
  resumeAttendanceResultSchema,
  startBreakEnvelopeSchema,
  startBreakRequestSchema,
  startBreakResultSchema,
  todayAttendanceEnvelopeSchema,
  todayAttendanceEstimateSchema,
  todayAttendanceSchema,
  todayAttendanceStateSchema,
  todayCalculationSchema,
  todayCalculationStatusSchema,
  todayTimelineEventSchema,
  type AttendanceCommand,
  type AttendanceCommandResult,
  type AttendanceState,
  type CalculationBlockerCode,
  type CalculationWarningCode,
  type ClockInRequest,
  type ClockInResult,
  type ClockOutRequest,
  type ClockOutResult,
  type ResumeAttendanceRequest,
  type ResumeAttendanceResult,
  type StartBreakRequest,
  type StartBreakResult,
  type TodayAttendance,
  type TodayAttendanceEstimate,
  type TodayTimelineEvent,
} from './today.js';
