import { workspacePackage as domainPackage } from '@workledger/domain';

export {
  createWorkLedgerAuthDatabase,
  type WorkLedgerAuthDatabase,
  type WorkLedgerAuthDatabaseConfiguration,
} from './auth-database.js';
export {
  createWorkLedgerDatabase,
  DatabaseClosedError,
  DatabaseConfigurationError,
  TransactionConfigurationError,
  type WorkLedgerDatabaseConfiguration,
} from './client.js';
export { DatabaseValueError } from './mapping/domain-values.js';
export {
  AbsenceCancellationLockedPeriodError,
  AbsenceCancellationReopenPeriodError,
} from './repositories/absence-cancellation-errors.js';
export { AuditValueError } from './repositories/audit-values.js';
export { IdempotencyValueError } from './repositories/idempotency-values.js';
export {
  DEVELOPMENT_SEED_ANCHOR_DATE,
  DEVELOPMENT_SEED_ORGANIZATION_ID,
  DevelopmentSeedError,
  seedDevelopmentDatabase,
  type DevelopmentSeedConfiguration,
  type DevelopmentSeedEnvironment,
  type DevelopmentSeedResult,
} from './seed/development.js';
export type {
  AccountSelfContextRecord,
  AccountSelfServiceRepository,
  AccountSessionRecord,
  ActivateAdministrationInvitationInput,
  AdministrationEmployeeAssignmentsRecord,
  AdministrationEmployeePageRecord,
  AdministrationEmployeeRecord,
  AdministrationEmploymentPeriodRecord,
  AdministrationManagerAssignmentRecord,
  AdministrationManagerCandidateRecord,
  AdministrationEmployeeScheduleRecord,
  AdministrationEmployeePolicyRecord,
  AdministrationAbsenceTypeRecord,
  AdministrationEntitlementEntryRecord,
  AdministrationPolicyAssignmentRecord,
  AdministrationTimePolicyRecord,
  AdministrationTimePolicyRules,
  AdministrationScheduleAssignmentRecord,
  AdministrationRepository,
  AdministrationSystemAccountPageRecord,
  AdministrationSystemAccountRecord,
  AdministrationTeamAssignmentRecord,
  AdministrationTeamPageRecord,
  AdministrationTeamRecord,
  AdministrationWeeklyScheduleRecord,
  ApplyAdministrationAssignmentTransitionInput,
  CreateAdministrationEmployeeInput,
  CreateAdministrationScheduleVersionInput,
  CreateAdministrationTechnicalAccountInput,
  AppendNotificationDeliveryAttemptInput,
  AppendNotificationInput,
  AbsenceCoverageSegmentInput,
  AbsenceCancellationRecord,
  AbsenceCancellationStatus,
  AbsenceCancellationDecisionAction,
  AbsenceCancellationDecisionResult,
  AbsenceCancellationPostLockAdjustmentRecord,
  AbsenceCancellationSnapshotLinkRecord,
  PersonalCalendarAbsenceRecord,
  PersonalCalendarHolidayRecord,
  PersonalCalendarRecords,
  AbsenceRequestRepository,
  ApprovalInboxRepository,
  ApprovalAbsenceRecord,
  ApprovalCancellationRecord,
  ApprovalInboxItemRecord,
  ApprovalInboxPageRecord,
  ApprovalInboxSort,
  ApprovalInboxStatus,
  ApprovalInboxTeamRecord,
  ApprovalInboxType,
  AbsenceRequestConfigurationInput,
  AppendDomainAuditEventInput,
  DecideAbsenceCancellationInput,
  AppendLeaveEntitlementEntryInput,
  AppendSecurityAuditEventInput,
  ApplicationRole,
  AdvanceAttendanceHeadInput,
  AppendPunchEvent,
  AppendTimeAccountEntryInput,
  AuditActor,
  AuditOutcome,
  AuditRepository,
  AttendanceIdempotencyClaim,
  AttendanceIdempotencyErrorSnapshot,
  AttendanceIdempotencyOutcome,
  AttendanceIdempotencyRepository,
  AttendanceIdempotencySuccessSnapshot,
  AttendanceHeadRecord,
  AttendanceRepository,
  AuthorizationActorRecord,
  AuthorizationChangeInput,
  AuthorizationRepository,
  ClaimAttendanceIdempotencyInput,
  CompleteAttendanceIdempotencyInput,
  CorrectionRequestRecord,
  CorrectionRequestRepository,
  CorrectionRequestStatus,
  CorrectionReviewRecord,
  DecisionActorAuthority,
  DecisionActorRecord,
  DecideAbsenceRequestInput,
  DecideCorrectionRequestInput,
  AppliedCorrectionRecord,
  ApplyCorrectionInput,
  AppendPostLockAdjustmentInput,
  CorrectionPostLockAdjustmentRecord,
  DailyProjectionRecord,
  DailyProjectionRepository,
  DailyProjectionStatus,
  DomainAuditEventRecord,
  DomainAuditFacts,
  DomainAuditTargetKind,
  EmployeeRecord,
  EmployeeRepository,
  EmployeeAuthorizationScope,
  EmployeeStatus,
  OrganizationRecord,
  OrganizationRepository,
  NotificationDeliveryOutcome,
  NotificationDestinationPath,
  NotificationDeliveryStatus,
  NotificationEvent,
  NotificationListItemRecord,
  NotificationPageRecord,
  NotificationRecord,
  NotificationRepository,
  ReportRepository,
  ReportDirection,
  ReportRangeInput,
  ReportSort,
  MonthlyTimeReportPage,
  MonthlyTimeReportRecord,
  FlexibleTimeReportPage,
  FlexibleTimeReportRecord,
  LeaveReportPage,
  LeaveReportRecord,
  MissingRecordReportPage,
  MissingRecordReportRecord,
  NotificationSourceKind,
  MonthlyPeriodBlockerSourceRecord,
  MonthlyAbsenceEffectSourceRecord,
  MonthlyAppliedCorrectionSourceRecord,
  MonthlyPeriodDecisionAction,
  MonthlyPeriodDecisionRecord,
  MonthlyPeriodProjectionSourceRecord,
  MonthlyPeriodProtectionStatus,
  MonthlyPeriodRangeRecord,
  MonthlyPeriodRecord,
  MonthlyPeriodRepository,
  MonthlyHolidaySourceRecord,
  MonthlyLedgerEntryRecord,
  MonthlyPolicyAssignmentRecord,
  MonthlyScheduleAssignmentRecord,
  PostLockAdjustmentRecord,
  LockedAbsenceCancellationEffectRecord,
  LockedAbsenceCancellationSnapshotRecord,
  ApprovedMonthlySnapshotRecord,
  AppendApprovedMonthlySnapshotInput,
  AppendMonthlyPeriodDecisionInput,
  SubmitMonthlyPeriodInput,
  SubmittedMonthlyPeriodRecord,
  TransitionMonthlyPeriodInput,
  ListNotificationsInput,
  DismissNotificationInput,
  LinkEmployeeInput,
  LeaveEntitlementEntryRecord,
  LeaveEntitlementRepository,
  ListAuthorizedEmployeesInput,
  ListApprovalInboxInput,
  ListDomainAuditEventsInput,
  ListSecurityAuditEventsInput,
  ListTeamStatusInput,
  ListTeamCalendarInput,
  ReplaceDailyProjectionInput,
  ReplaceActiveRolesInput,
  SecurityAuditEventRecord,
  SubmitCorrectionRequestInput,
  SubmitAbsenceCancellationInput,
  SecurityAuditFacts,
  SecurityAuditTargetKind,
  StoredPunchEvent,
  TimeAccountRepository,
  TeamAvailabilityState,
  TeamCalendarEntryRecord,
  TeamStatusMemberRecord,
  TeamStatusRepository,
  TodayAttendanceRepository,
  TodayAttendanceSourceInput,
  TodayAttendanceSourceRecord,
  TodayHolidayRecord,
  SubmitVacationRequestInput,
  SubmitSicknessReportInput,
  SicknessReportRecord,
  VacationAbsenceTypeRecord,
  VacationRequestConfigurationRecord,
  VacationRequestRecord,
  WithdrawAbsenceCancellationInput,
} from './repositories/contracts.js';
export type {
  TransactionIsolationLevel,
  TransactionOptions,
  TransactionRetry,
  WorkLedgerDatabase,
  WorkLedgerTransaction,
} from './transactions/contracts.js';

export const workspacePackage = '@workledger/database' as const;
export const workspaceDependencies = [domainPackage] as const;

export type WorkspacePackageName = typeof workspacePackage;
export type WorkspaceDependencyName = (typeof workspaceDependencies)[number];
